version: '3.9'

services:
    db:
        container_name: pg_db
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            -   ./postgres_data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
    pgadmin4:
        container_name: pgadmin4
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: postgres@p.ru
            PGADMIN_DEFAULT_PASSWORD: postgres
        ports:
            - "5050:80"